### ISSUE TITLE
Splits in Loops of DamageCrosses

### ISSUE THREAD

**Issue by MasterNO122333** [GCer-Hidenori/MinerGunBuilderCalculator#106]
If there is a split in a loop of a Damage cross the calculation doesnt work anymore, it just removes the effect of the cross completly

**Comment by GCer-Hidenori** [comment]
Thanks for the report. I will check it out.

**Comment by GCer-Hidenori** [comment]
![image](https://user-images.githubusercontent.com/3679076/157791487-d319571c-6539-4283-9f41-990292ade427.png)
Lowest damage etc. should be 2.
