### ISSUE TITLE
[feat]support Combine 10's skill.Higher damage of current or previous projectile gets instead combined.

### ISSUE THREAD

**Issue by GCer-Hidenori** [GCer-Hidenori/MinerGunBuilderCalculator#62]

**Comment by GCer-Hidenori** [comment]
feat with https://github.com/GCer-Hidenori/MinerGunBuilderCalculator/commit/e543dd8e423632adee9b658f0f35cca0a733ec94

**Comment by MasterNO122333** [comment]
The skill still doesn't work, it does nothing when you choose it

**Comment by GCer-Hidenori** [comment]
Thanks for letting me know.
I fixed it.
